# Generated by Django 6.1 on 2026-08-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
